runtime: aspnetcore
env: flex

service: default

env_variables:
  # Add any environment variables required by your application

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
- url: /.*
  script: auto
  secure: always
