name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Restore NuGet packages
      run: dotnet restore
      working-directory: ./YourProjectName
    - name: Build for Android
      run: msbuild /t:Restore,Build /p:Configuration=Release /p:Platform="Android" YourProjectName.sln
      working-directory: ./
    - name: Build for iOS
      run: msbuild /t:Restore,Build /p:Configuration=Release /p:Platform="iPhone" YourProjectName.sln
      working-directory: ./
    - name: Build for UWP
      run: msbuild /t:Restore,Build /p:Configuration=Release /p:Platform="UAP" YourProject
