name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Restore NuGet packages
      run: dotnet restore
      working-directory: ./ProjectV1VB
    - name: Build for Android
      run: msbuild /t:Restore,Build /p:Configuration=Debug /p:Platform="Any CPU" ProjectV1VB.Android.csproj
      working-directory: ./ProjectV1VB.Android
    - name: Build for iOS
      run: msbuild /t:Restore,Build /p:Configuration=Debug /p:Platform="iPhoneSimulator" ProjectV1VB.iOS.csproj
      working-directory: ./ProjectV1VB.iOS
    - name: Build for UWP
      run: msbuild /t:Restore,Build /p:Configuration=Debug /p:Platform="x86" ProjectV1VB.UWP.csproj
      working-directory: ./ProjectV1VB.UWP
    - name: Run Android tests
      run: vstest.console.exe ProjectV1VB.Android.Tests.dll
      working-directory: ./ProjectV1VB.Android.Tests/bin/Debug/net6.0
    - name: Run iOS tests
      run: vst
