name: CI/CD Workflow

on:
  push:
    branches:
      - MainEMSCompleted

  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Clear NuGet package cache
        run: dotnet nuget locals all --clear

      - name: Restore NuGet packages
        run: dotnet restore ATUProject1/EmployeeManagementSystem/EmployeeManagementSystem.csproj

      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore ATUProject1/EmployeeManagementSystem/EmployeeManagementSystem.csproj

  test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet: ['7.0.x']
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Run tests
        run: dotnet test --no-build --verbosity normal ATUProject1/EmployeeManagementSystem/EmployeeManagementSystem.csproj

  dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Run Dependabot
        uses: dependabot/dependabot-core@2.x
        with:
         args: --package-ecosystem nuget --directory /ATUProject1/EmployeeManagementSystem
