name: CI/CD Workflow

on:
  push:
    branches:
      - DevOpsCA

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.0'

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --no-build --verbosity normal
