name: 'OSSAR analysis'

on:
  push:
    branches:
      - MainEMSCompleted
  pull_request:
    branches:
      - MainEMSCompleted

jobs:
  analyze:
    name: Analyze
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run OSSAR analysis
        id: ossar
        uses: github/ossar-action@v1
        with:
          upload: true  # Set upload to true to generate and upload the reports

      - name: Upload OSSAR reports
        uses: actions/upload-artifact@v2
        with:
          name: OSSAR reports
          path: ${{ steps.ossar.outputs.report_directory }}
