name: .NET Core OSSAR Analysis

on:
  push:
    branches: [ "MainEMSCompleted", newmainbranchrule ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "MainEMSCompleted" ]
  schedule:
    - cron: '43 19 * * 1'

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0' # specify the version of .NET core required for your project

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run OSSAR
      uses: github/ossar-action@v1
      id: ossar

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.ossar.outputs.sarifFile }}
