name: OWASP Dependency Track check

on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: OWASP Dependency Track check
        uses: Quobis/action-owasp-dependecy-track-check@v1.3

