name: OWASP Dependency Check

on: [push, pull_request]

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: OWASP Dependency Check
        uses: dependency-check/dependency-check-action@v3
        with:
          scan-type: 'dotnet'
          output-format: 'ALL'
          project-name: 'Your Project Name'
