name: Documentation Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Generate Swagger JSON
        run: dotnet swagger tofile --output ./swagger.json --yaml --no-pretty

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./swagger-ui  # Replace with the directory containing your Swagger UI files

