name: ZAP Scan

on:
  push:
    branches: [ main, MainEMSCompleted ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: OWASP ZAP Scan
      uses: zaproxy/action-baseline@v0.4.0
      with:
        target: 'https://your-website-url.com'
